---
version: '3'
volumes:
  postgresql_data:
  ldap_data:
  ldap_config:
  geoserver_geodata:
  geoserver_datadir:
  geoserver_tiles:
  geoserver_native_libs:

services:
  front-server:
    image: ${DOCKER_BASE}-front-server:${DOCKER_TAG}
    volumes:
      - ${PWD}/app/featurereports/static/admin:/app
    ports:
      - 3000:3000

  database:
    image: georchestra/database
    restart: unless-stopped

  db:
    image: ${DOCKER_BASE}-db:${DOCKER_TAG}
    restart: unless-stopped
    environment:
      - POSTGRES_USER=featurereports
      - POSTGRES_PASSWORD=featurereports
      - POSTGRES_DB=featurereports

  app:
    image: ${DOCKER_BASE}-backend:${DOCKER_TAG}
    user: www-data
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - PGHOST
      - PGHOST_SLAVE
      - PGPORT
      - PGUSER
      - PGPASSWORD
      - PGDATABASE
      - PGOPTIONS
      - INI_FILE
      - PROXY_PREFIX
      - GEOSERVER_URL
    ports:
      - ${DOCKER_PORT}:8080

  db_tests:
    image: ${DOCKER_BASE}-db:${DOCKER_TAG}
    restart: unless-stopped
    environment:
      - POSTGRES_USER=featurereports
      - POSTGRES_PASSWORD=featurereports
      - POSTGRES_DB=featurereports_tests

  app-tools:
    image: ${DOCKER_BASE}-backend-tools:${DOCKER_TAG}
    user: www-data
    restart: unless-stopped
    depends_on:
      - db_tests
    volumes:
      - ${PWD}/app/featurereports:/app/featurereports
      - ${PWD}/app/tests:/app/tests
    environment:
      - PGHOST=db_tests
      - PGHOST_SLAVE=db_tests
      - PGPORT
      - PGUSER
      - PGPASSWORD
      - PGDATABASE=featurereports_tests
      - GEOSERVER_URL
      - INI_FILE
    command: 'tail -f /dev/null'

  lb:
    image: traefik:1.7
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./georchestra_resources/ssl/:/etc/traefik/ssl
      - ./georchestra_resources/traefik.toml:/traefik.toml

  ldap:
    build:
      context: georchestra_resources/ldap
    environment:
        - SLAPD_ORGANISATION=georchestra
        - SLAPD_DOMAIN=georchestra.org
        - SLAPD_PASSWORD=secret
        - SLAPD_LOG_LEVEL=32768 # See https://www.openldap.org/doc/admin24/slapdconfig.html#loglevel%20%3Clevel%3E
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap
      - ./georchestra_resources/role_report_admin.ldif:/docker-entrypoint.d/role_report_admin.ldif
    restart: always
    ports:
      - "389:389"

  proxy:
    image: georchestra/security-proxy:latest
    depends_on:
      - ldap
      - database
    volumes:
      - ./georchestra_datadir:/etc/georchestra
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - XMS=256M
      - XMX=512M
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sp"
      - "traefik.frontend.rule=Host:georchestra.mydomain.org"
      - "traefik.frontend.passHostHeader=true"

  cas:
    image: georchestra/cas:latest
    depends_on:
      - ldap
    volumes:
      - ./georchestra_datadir:/etc/georchestra
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - XMS=256M
      - XMX=512M
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.backend=cas"
      - "traefik.frontend.rule=Host:georchestra.mydomain.org;PathPrefix:/cas"

  header:
    image: georchestra/header:latest
    volumes:
      - ./georchestra_datadir:/etc/georchestra
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - XMS=256M
      - XMX=512M
    restart: always

  geoserver:
    image: georchestra/geoserver:latest
    depends_on:
      - ldap
    volumes:
      - ./georchestra_datadir:/etc/georchestra
      - geoserver_datadir:/mnt/geoserver_datadir
      - geoserver_geodata:/mnt/geoserver_geodata
      - geoserver_tiles:/mnt/geoserver_tiles
      - geoserver_native_libs:/mnt/geoserver_native_libs
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - XMS=256M
      - XMX=8G
    restart: always

  mapstore:
    image: camptocamp/mapstore2-georchestra:1.1
    depends_on:
      - database
    volumes:
      - ./georchestra_datadir:/etc/georchestra
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m -XX:MaxPermSize=128m -Dgeorchestra.datadir=/etc/georchestra -DPRINT_BASE_URL=pdf

  console:
    image: georchestra/console:latest
    depends_on:
      - database
    volumes:
      - ./georchestra_datadir:/etc/georchestra
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - XMS=256M
      - XMX=8G
    restart: always
