---

# The project Docker compose file for development.

version: '3'

services:

  backend:
    image: ${DOCKER_BASE}-backend-tools:${DOCKER_TAG}
    volumes:
      - ${PWD}/app/featurereports:/app/featurereports
      - ${PWD}/app/tests:/app/tests
    command: pserve --reload c2c://featurereports.ini

  front-server:
    image: ${DOCKER_BASE}-front-server:${DOCKER_TAG}
    volumes:
      - ${PWD}/app/featurereports/static/admin:/app
    ports:
      - 3000:3000