---

name: Continuous integration

on:
  push:

jobs:
  main:
    name: Continuous integration
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: make build
      - name: Backend packages
        run: docker run camptocamp/featurereports-backend-tools:latest pip freeze
      - name: Frontend lint
        run: docker run -e CI=TRUE camptocamp/featurereports-backend-front-server:latest npm run check
      - name: Backend lint
        run: make check
      - name: Frontend tests
        run: docker run -e CI=TRUE camptocamp/featurereports-backend-front-server:latest npm run test
      - name: Backend tests
        run: make test
      - name: Docker compose logs
        if: ${{ always() }}
        run: |
          docker-compose logs
